vim.keymap.set("n", "<leader>bc", function ()
    vim.cmd.tabnew()
    vim.cmd.terminal("cmake . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1")
end, {})
vim.keymap.set("n", "<leader>bb", function ()
    vim.cmd.tabnew()
    vim.cmd.terminal("ninja -C build")
end, {})
vim.keymap.set("n", "<leader>bt", function ()
    vim.cmd.tabnew()
    vim.cmd.terminal("PYTHONPATH=/Users/jd/hax/cpp-onnx-python/build/ /Users/jd/venv/bin/python ./test/test.py")
end, {})
